import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Header from "../components/Header";
import Benefits from "../components/benefits";
import styles from "../styles/Home.module.scss";
import About_us from "../components/About_us";
import Choose_us from "../components/Choose_us";
import Team from "../components/Team";
import Packages from "../components/Packages";
import Contact_us from "../components/Contact_us";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar></Navbar>
        <Header></Header>
        <Benefits></Benefits>
        <About_us></About_us>
        <Choose_us></Choose_us>
        <Team></Team>
        <Packages></Packages>
        <Contact_us></Contact_us>
        <Footer></Footer>
      </main>
    </div>
  );
}
