import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className='header'>
          <div className='logo__container'>
            <Image className="logo__container-img" src={'/logo.png'} width={800} height={500}></Image>
          </div>

        </div>

  
      </main>

    
    </div>
  )
}
